### PR TITLE
portalocker v1.7.1

### PR DESCRIPTION
**Pull request by maresb**
My goal is to render a python 3.10 build of portalocker v1.x.

I've marked this PR as Draft because I'd like to merge it to a branch named `v1.x`.

Could you please create a new branch with that name on the commit 9b2e5b914c40a7d72e9 which I could target with this PR?

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@sodre and @tyrius02, ready for review. Please create the branch described in the description if that's okay, thanks!

**Comment by tyrius02** [comment]
@maresb I've created a v1.7.x branch rather than 1.x. It looks like 1.0.x already exists, and I think this is consistent with what I'd done previously.

**Review by tyrius02 — APPROVED** [review]
looks good to me

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@tyrius02, thanks so much for the speedy response and setting up that branch for me!

It's also unclear to me how to apply the migrations for that branch, so I [asked on Gitter](https://gitter.im/conda-forge/conda-forge.github.io?at=619ab72a42fc2863b21e4707). I have a hunch, but I'd like to confirm it.

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Let's merge this now. It will not yet build for 3.10, but at least the `v1.7.x` branch will have the latest version for when the migrations are triggered by #48.

**Comment by maresb** [comment]
Many thanks @tyrius02! With this we had further success upstream: https://github.com/conda-forge/dvc-feedstock/pull/245

**Pull request merged**
